# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 11111111

# 配置tomcat
server:
  servlet:
    context-path: /mybatis
  port: 8085

# 指定mybatis映射文件地址：
mybatis:
  mapper-locations: classpath:mapper/*.xml